### ISSUE TITLE
npm ERR! phantomjs@1.9.20 install: `node install.js`

### ISSUE THREAD

**Issue by amitesh-gaurav** [mozilla/seasponge#83]
Hi, I encountered the following error, while installing node dependencies using "npm install" command.
Following is the detailed error message from debug.log.
```
1252 verbose stack Error: phantomjs@1.9.20 install: `node install.js`
1252 verbose stack Exit status 1
1252 verbose stack     at EventEmitter.<anonymous> (C:\Users\amitesh_gaurav\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:283:16)
1252 verbose stack     at emitTwo (events.js:106:13)
1252 verbose stack     at EventEmitter.emit (events.js:191:7)
1252 verbose stack     at ChildProcess.<anonymous> (C:\Users\amitesh_gaurav\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
1252 verbose stack     at emitTwo (events.js:106:13)
1252 verbose stack     at ChildProcess.emit (events.js:191:7)
1252 verbose stack     at maybeClose (internal/child_process.js:885:16)
1252 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
I found "npm set strict-ssl false" should fix this issue, but it's not working for me.
I'm working behind a corporate proxy. Could it be blocking certain packages from installing?
Please suggest fixes.

**Comment by amitesh-gaurav** [comment]
Hi, closing the issue as It was due to network firewall.
